package com.warpy.app.localization

import com.warpy.app.model.AppLanguage
import java.util.Locale

internal fun resolveAppLanguage(
    selected: AppLanguage,
    @Suppress("UNUSED_PARAMETER") systemLanguage: String = Locale.getDefault().language,
): AppLanguage = selected

internal object WarpyLocalization {
    private val english = mapOf(
        "Авто" to "Auto",
        "Блокировать рекламу" to "Block ads",
        "Буфер обмена пуст." to "Clipboard is empty.",
        "Включить VPN" to "Connect VPN",
        "Включен" to "On",
        "Все приложения" to "All applications",
        "Все сайты" to "All websites",
        "Все сайты используют VPN" to "All websites use the VPN",
        "Вставить из буфера" to "Import from clipboard",
        "Выберите приложения для туннелирования" to "Select applications for tunneling",
        "выбран" to "selected",
        "Выбрать режим туннелирования" to "Select tunneling mode",
        "Выбрать, какие приложения используют VPN" to "Choose which applications use the VPN",
        "Выключено" to "Disconnected",
        "Выключен" to "Off",
        "Выключить VPN" to "Disconnect VPN",
        "Добавить профиль" to "Add profile",
        "Добавьте профиль" to "Add a profile",
        "Добавьте профиль кнопкой +" to "Add a profile with the + button",
        "Доступна версия" to "Version available",
        "Добавить сайт" to "Add website",
        "Добавьте сайты для отдельного правила" to "Add websites for a separate rule",
        "Добавьте сайты для туннелирования" to "Add websites for tunneling",
        "Добавленные сайты идут напрямую" to "Added websites connect directly",
        "Скачиваем обновление" to "Downloading update",
        "Разрешите установку обновления" to "Allow update installation",
        "Не удалось установить обновление" to "Could not install update",
        "Warpy обновится и снова откроется" to "Warpy will update and reopen",
        "Позже" to "Later",
        "Обновить" to "Update",
        "Повторить" to "Retry",
        "Загрузка..." to "Downloading...",
        "Дополнительная фильтрация рекламы и трекеров" to "Additional ad and tracker filtering",
        "Дополнительно" to "Advanced",
        "Доступ к домашней сети" to "Local network access",
        "Загрузка подписки..." to "Loading subscription...",
        "Загрузка приложений..." to "Loading applications...",
        "Интерфейс" to "Interface",
        "Закрепить Warpy в системных настройках Android" to "Keep Warpy enabled in Android VPN settings",
        "Закрыть" to "Close",
        "Закрыть список профилей" to "Close profile list",
        "Замерить скорость" to "Run speed test",
        "Запуск вместе с телефоном" to "Start with the phone",
        "Запустить" to "Start",
        "Защита" to "Protection",
        "Идет тест" to "Testing...",
        "Исключить выбранные" to "Exclude selected",
        "Исключить системные" to "Exclude system applications",
        "КБ/с" to "KB/s",
        "Мбит/с" to "Mbps",
        "мс" to "ms",
        "Наведите камеру на QR-код профиля" to "Point the camera at a profile QR code",
        "Нажмите + сверху, чтобы добавить первый профиль." to "Tap + above to add your first profile.",
        "Назад" to "Back",
        "Настройки" to "Settings",
        "Не удалось проверить обновления" to "Could not check for updates",
        "Не удалось восстановить предыдущий профиль" to "Could not restore the previous profile",
        "Не удалось восстановить соединение после переключения профиля" to "Could not restore the connection after switching profiles",
        "Не удалось выбрать активный профиль" to "Could not select the active profile",
        "Не удалось выбрать новый профиль" to "Could not select the new profile",
        "Не удалось запустить VPN" to "Could not start VPN",
        "Не удалось подключиться" to "Could not connect",
        "Не удалось подключиться к новому профилю" to "Could not connect to the new profile",
        "Не удалось подтвердить обмен данными через VPN-туннель" to "Could not verify traffic through the VPN tunnel",
        "Не удалось прочитать настройки VPN" to "Could not read VPN settings",
        "Не удалось разобрать профили из подписки" to "Could not parse profiles from the subscription",
        "Не удалось разобрать ссылки" to "Could not parse the links",
        "Не удалось распознать ссылку. Поддерживаются VLESS, Hysteria2 и Trojan." to
            "Could not recognize the link. VLESS, Hysteria2 and Trojan are supported.",
        "Не удалось сохранить настройки" to "Could not save settings",
        "Не удалось установить соединение" to "Could not establish a connection",
        "Нет профиля" to "No profile",
        "Ничего не найдено" to "Nothing found",
        "Ограничения батареи" to "Battery restrictions",
        "Ожидание сети" to "Waiting for network",
        "Остановка VPN" to "Stopping VPN",
        "Ответ подписки слишком большой" to "Subscription response is too large",
        "Открывать роутер и устройства в локальной сети напрямую" to
            "Access the router and local devices directly",
        "Открыть список профилей" to "Open profile list",
        "Отмена" to "Cancel",
        "Отменено" to "Cancelled",
        "Отмеченные приложения идут напрямую" to "Selected applications connect directly",
        "Ошибка" to "Error",
        "Ошибка доступа к VPN интерфейсу" to "Could not access the VPN interface",
        "Ошибка запуска ядра VPN" to "VPN core failed to start",
        "Ошибка конфигурации профиля" to "Profile configuration error",
        "Ошибка подключения к VPN" to "VPN connection failed",
        "Ошибка: Порт занят другим приложением" to "Error: the port is used by another application",
        "Пинг" to "Ping",
        "Поддерживаются vless://, hysteria2:// и trojan:// профили." to
            "vless://, hysteria2:// and trojan:// profiles are supported.",
        "Поделиться профилем" to "Share profile",
        "Подключение" to "Connection",
        "Подключение..." to "Connecting...",
        "Подключено" to "Connected",
        "ПОДКЛЮЧЕНО" to "CONNECTED",
        "Подробности подключения и отчет для диагностики" to "Connection details and diagnostic report",
        "Поиск" to "Search",
        "Показать QR" to "Show QR code",
        "Последние события" to "Recent events",
        "Постоянный VPN" to "Always-on VPN",
        "Превышено время ожидания сервера" to "Server timed out",
        "Приложения" to "Applications",
        "Проверить обновления" to "Check for updates",
        "Проверяем обновления..." to "Checking for updates...",
        "Проверить профиль" to "Check profile",
        "Проверка..." to "Checking...",
        "Проверяем профиль" to "Checking profile",
        "Проверяем профиль..." to "Checking profile...",
        "Протокол" to "Protocol",
        "Профили" to "Profiles",
        "Профиль" to "Profile",
        "Профиль не выбран." to "No profile selected.",
        "Профиль не настроен или конфиг пустой" to "The profile is incomplete or its configuration is empty",
        "Профиль не подключился: TLS-сертификат не совпадает с SNI" to
            "The profile failed: the TLS certificate does not match the SNI",
        "Профиль не подключился: сервер не отвечает" to "The profile failed: the server is not responding",
        "Профиль не подключился: сервер не принял Hysteria2 handshake; проверьте SNI, пароль и obfs" to
            "The profile failed: the server rejected the Hysteria2 handshake; check SNI, password and obfs",
        "Профиль не подключился: сервер отклонил данные авторизации" to
            "The profile failed: the server rejected the credentials",
        "Профиль не подключился: сервер отклонил соединение" to
            "The profile failed: the server rejected the connection",
        "Профиль удалён" to "Profile deleted",
        "Пустой конфиг VPN" to "VPN configuration is empty",
        "Развернуть" to "Expand",
        "Размер сетевых пакетов. Изменение применится при следующем подключении" to
            "Network packet size. The change applies on the next connection",
        "Разрешить Android не останавливать VPN" to "Allow Android to keep the VPN running",
        "Свернуть" to "Collapse",
        "Сейчас замеряем: загрузку" to "Measuring download speed",
        "Сейчас замеряем: отдачу" to "Measuring upload speed",
        "Сейчас замеряем: пинг" to "Measuring latency",
        "Сервер" to "Server",
        "Сервер временно не отвечает" to "The server is temporarily unavailable",
        "Сервер временно отклонил соединение" to "The server temporarily rejected the connection",
        "Сетевые параметры" to "Network settings",
        "Сканировать QR камерой" to "Scan QR code with camera",
        "Скопировать в буфер" to "Copy to clipboard",
        "Скопировать отчет" to "Copy report",
        "Скорость" to "Speed",
        "Скрывать базовую рекламу и трекеры через DNS" to "Filter common ads and trackers through DNS",
        "Сначала включите VPN" to "Connect the VPN first",
        "Сначала добавьте профиль" to "Add a profile first",
        "Совместимость QUIC" to "QUIC compatibility",
        "Соединение восстанавливается" to "Restoring connection",
        "Соединение отклонено сервером" to "The server rejected the connection",
        "Состояние" to "Status",
        "Состояние и диагностика" to "Status and diagnostics",
        "Спидтест недоступен: локальный proxy не отвечает" to "Speed test unavailable: the local proxy is not responding",
        "Список пуст" to "List is empty",
        "Стабильное соединение" to "Stable connection",
        "Статус" to "Status",
        "Считать QR из изображения" to "Read QR code from image",
        "Тест неполный" to "Test incomplete",
        "Только выбранные" to "Only selected",
        "Туннелирование" to "Tunneling",
        "Отдельные правила для приложений и сайтов" to "Separate rules for applications and websites",
        "Сайты" to "Websites",
        "Скачиваем обновление" to "Downloading update",
        "Установлена версия" to "Installed version",
        "Удалить сайт" to "Remove website",
        "Через VPN идут только добавленные сайты" to "Only added websites use the VPN",
        "Удалить" to "Delete",
        "Удалить профиль" to "Delete profile",
        "Удалить профиль?" to "Delete profile?",
        "Улучшить работу YouTube" to "Improve YouTube access",
        "Устанавливаем туннель" to "Establishing tunnel",
        "Фоновая работа" to "Background operation",
        "Через VPN идут только отмеченные приложения" to "Only selected applications use the VPN",
        "Язык" to "Language",
        "Как в системе" to "System",
        "Язык интерфейса Warpy" to "Warpy interface language",
        "Android не выдал разрешение на VPN" to "Android did not grant VPN permission",
        "Android не открыл запрос разрешения VPN" to "Android could not open the VPN permission request",
        "Android требует разрешение на VPN" to "Android requires VPN permission",
        "Конфиг пустой." to "The configuration is empty.",
        "Автоматически восстанавливать VPN после сна и смены сети" to
            "Automatically restore VPN after sleep and network changes",
        "Включать VPN после перезагрузки, если он работал" to
            "Reconnect after a reboot when VPN was previously active",
        "Использовать TCP вместо QUIC и HTTP/3 при проблемах с сайтами" to
            "Use TCP instead of QUIC and HTTP/3 when websites are unstable",
        "MTU и совместимость соединения" to "MTU and connection compatibility",
        "Warpy может работать в фоне без ограничений" to "Warpy can run in the background without restrictions",
        "VPN выключен" to "VPN is off",
        "VPN не запустился" to "VPN failed to start",
        "VPN не запустился: внутренний сервис не ответил" to "VPN failed to start: the internal service did not respond",
        "VPN не запустился: локальный порт проверки занят" to "VPN failed to start: the local test port is in use",
        "VPN работает" to "VPN is running",
        "VPN работает для всего телефона" to "VPN is used by the entire phone",
        "Запускаем VPN" to "Starting VPN",
        "Восстанавливаем VPN" to "Restoring VPN",
        "QR найден, но это не профиль VLESS/Hysteria2" to "The QR code is not a VLESS or Hysteria2 profile",
    )

    private val chineseSimplified = mapOf(
        "Авто" to "自动",
        "Блокировать рекламу" to "拦截广告",
        "Буфер обмена пуст." to "剪贴板为空。",
        "Включить VPN" to "连接 VPN",
        "Включен" to "已开启",
        "Все приложения" to "所有应用",
        "Вставить из буфера" to "从剪贴板导入",
        "Выберите приложения для туннелирования" to "选择需要使用 VPN 的应用",
        "выбран" to "已选择",
        "Выбрать режим туннелирования" to "选择隧道模式",
        "Выбрать, какие приложения используют VPN" to "选择哪些应用使用 VPN",
        "Выключено" to "未连接",
        "Выключен" to "已关闭",
        "Выключить VPN" to "断开 VPN",
        "Добавить профиль" to "添加配置",
        "Добавьте профиль" to "请添加配置",
        "Добавьте профиль кнопкой +" to "点击 + 添加配置",
        "Дополнительная фильтрация рекламы и трекеров" to "进一步过滤广告和跟踪器",
        "Дополнительно" to "高级",
        "Доступ к домашней сети" to "访问本地网络",
        "Загрузка подписки..." to "正在加载订阅…",
        "Загрузка приложений..." to "正在加载应用…",
        "Интерфейс" to "界面",
        "Закрепить Warpy в системных настройках Android" to "在 Android VPN 设置中保持 Warpy 启用",
        "Закрыть" to "关闭",
        "Закрыть список профилей" to "关闭配置列表",
        "Замерить скорость" to "测速",
        "Запуск вместе с телефоном" to "开机启动",
        "Запустить" to "开始",
        "Защита" to "保护",
        "Идет тест" to "测试中…",
        "Исключить выбранные" to "排除所选应用",
        "Исключить системные" to "排除系统应用",
        "КБ/с" to "KB/s",
        "Мбит/с" to "Mbps",
        "мс" to "毫秒",
        "Наведите камеру на QR-код профиля" to "将相机对准配置二维码",
        "Нажмите + сверху, чтобы добавить первый профиль." to "点击上方的 + 添加第一个配置。",
        "Назад" to "返回",
        "Настройки" to "设置",
        "Не удалось запустить VPN" to "无法启动 VPN",
        "Не удалось подключиться" to "无法连接",
        "Не удалось подключиться к новому профилю" to "无法连接到新配置",
        "Не удалось разобрать профили из подписки" to "无法解析订阅中的配置",
        "Не удалось разобрать ссылки" to "无法解析链接",
        "Нет профиля" to "无配置",
        "Ничего не найдено" to "未找到内容",
        "Ограничения батареи" to "电池限制",
        "Ожидание сети" to "等待网络",
        "Остановка VPN" to "正在停止 VPN",
        "Открывать роутер и устройства в локальной сети напрямую" to "直接访问路由器和本地设备",
        "Открыть список профилей" to "打开配置列表",
        "Отмена" to "取消",
        "Отменено" to "已取消",
        "Отмеченные приложения идут напрямую" to "所选应用直接连接",
        "Ошибка" to "错误",
        "Пинг" to "延迟",
        "Поделиться профилем" to "分享配置",
        "Подключение" to "连接",
        "Подключение..." to "正在连接…",
        "Подключено" to "已连接",
        "ПОДКЛЮЧЕНО" to "已连接",
        "Подробности подключения и отчет для диагностики" to "连接详情和诊断报告",
        "Подключиться к новому профилю?" to "连接到新配置？",
        "Подключиться" to "连接",
        "Оставить текущий" to "保持当前连接",
        "Поиск" to "搜索",
        "Показать QR" to "显示二维码",
        "Последние события" to "最近事件",
        "Постоянный VPN" to "始终开启 VPN",
        "Приложения" to "应用",
        "Профили" to "配置",
        "Профиль" to "配置",
        "Профиль удалён" to "配置已删除",
        "Развернуть" to "展开",
        "Разрешить Android не останавливать VPN" to "允许 Android 保持 VPN 运行",
        "Свернуть" to "收起",
        "Сервер" to "服务器",
        "Сетевые параметры" to "网络参数",
        "Сканировать QR камерой" to "扫描二维码",
        "Скопировать в буфер" to "复制到剪贴板",
        "Скопировать отчет" to "复制报告",
        "Скорость" to "速度",
        "Скрывать базовую рекламу и трекеры через DNS" to "通过 DNS 过滤常见广告和跟踪器",
        "Сначала включите VPN" to "请先连接 VPN",
        "Сначала добавьте профиль" to "请先添加配置",
        "Совместимость QUIC" to "QUIC 兼容性",
        "Соединение восстанавливается" to "正在恢复连接",
        "Состояние" to "状态",
        "Состояние и диагностика" to "状态与诊断",
        "Список пуст" to "列表为空",
        "Стабильное соединение" to "稳定连接",
        "Статус" to "状态",
        "Считать QR из изображения" to "从图片读取二维码",
        "Только выбранные" to "仅所选应用",
        "Туннелирование" to "隧道设置",
        "Удалить" to "删除",
        "Удалить профиль" to "删除配置",
        "Удалить профиль?" to "删除配置？",
        "Улучшить работу YouTube" to "改善 YouTube 访问",
        "Устанавливаем туннель" to "正在建立隧道",
        "Фоновая работа" to "后台运行",
        "Через VPN идут только отмеченные приложения" to "仅所选应用使用 VPN",
        "Язык" to "语言",
        "Как в системе" to "跟随系统",
        "Язык интерфейса Warpy" to "Warpy 界面语言",
        "Русский" to "Русский",
        "Запускаем VPN" to "正在启动 VPN",
        "Восстанавливаем VPN" to "正在恢复 VPN",
        "VPN выключен" to "VPN 已关闭",
        "VPN работает" to "VPN 正在运行",
        "VPN работает для всего телефона" to "VPN 用于整台手机",
        "Автоматически восстанавливать VPN после сна и смены сети" to "在休眠或切换网络后自动恢复 VPN",
        "Включать VPN после перезагрузки, если он работал" to "设备重启后恢复之前的 VPN 连接",
        "Использовать TCP вместо QUIC и HTTP/3 при проблемах с сайтами" to "网站不稳定时使用 TCP 替代 QUIC 和 HTTP/3",
        "MTU и совместимость соединения" to "MTU 与连接兼容性",
        "Warpy может работать в фоне без ограничений" to "Warpy 可不受限制地在后台运行",
        "Не удалось восстановить предыдущий профиль" to "无法恢复之前的配置",
        "Не удалось восстановить соединение после переключения профиля" to "切换配置后无法恢复连接",
        "Не удалось выбрать активный профиль" to "无法选择当前配置",
        "Не удалось выбрать новый профиль" to "无法选择新配置",
        "Не удалось подтвердить обмен данными через VPN-туннель" to "无法确认 VPN 隧道中的数据传输",
        "Не удалось прочитать настройки VPN" to "无法读取 VPN 设置",
        "Не удалось распознать ссылку. Поддерживаются VLESS, Hysteria2 и Trojan." to "无法识别链接。支持 VLESS、Hysteria2 和 Trojan。",
        "Не удалось сохранить настройки" to "无法保存设置",
        "Не удалось установить соединение" to "无法建立连接",
        "Ответ подписки слишком большой" to "订阅响应过大",
        "Ошибка доступа к VPN интерфейсу" to "无法访问 VPN 接口",
        "Ошибка запуска ядра VPN" to "VPN 核心启动失败",
        "Ошибка конфигурации профиля" to "配置设置错误",
        "Ошибка подключения к VPN" to "VPN 连接错误",
        "Ошибка: Порт занят другим приложением" to "错误：端口已被其他应用占用",
        "Поддерживаются vless://, hysteria2:// и trojan:// профили." to "支持 vless://、hysteria2:// 和 trojan:// 配置。",
        "Превышено время ожидания сервера" to "服务器响应超时",
        "Проверить профиль" to "检查配置",
        "Проверка..." to "正在检查…",
        "Проверяем профиль" to "检查配置",
        "Проверяем профиль..." to "正在检查配置…",
        "Протокол" to "协议",
        "Профиль не выбран." to "未选择配置。",
        "Профиль не настроен или конфиг пустой" to "配置未设置或内容为空",
        "Профиль не подключился: TLS-сертификат не совпадает с SNI" to "连接失败：TLS 证书与 SNI 不匹配",
        "Профиль не подключился: сервер не отвечает" to "连接失败：服务器无响应",
        "Профиль не подключился: сервер не принял Hysteria2 handshake; проверьте SNI, пароль и obfs" to "连接失败：服务器拒绝 Hysteria2 握手；请检查 SNI、密码和混淆设置",
        "Профиль не подключился: сервер отклонил данные авторизации" to "连接失败：服务器拒绝身份验证信息",
        "Профиль не подключился: сервер отклонил соединение" to "连接失败：服务器拒绝连接",
        "Пустой конфиг VPN" to "VPN 配置为空",
        "Размер сетевых пакетов. Изменение применится при следующем подключении" to "网络数据包大小。更改将在下次连接时生效",
        "Сейчас замеряем: загрузку" to "正在测量：下载速度",
        "Сейчас замеряем: отдачу" to "正在测量：上传速度",
        "Сейчас замеряем: пинг" to "正在测量：延迟",
        "Сервер временно не отвечает" to "服务器暂时无响应",
        "Сервер временно отклонил соединение" to "服务器暂时拒绝连接",
        "Соединение отклонено сервером" to "服务器拒绝了连接",
        "Спидтест недоступен: локальный proxy не отвечает" to "测速不可用：本地代理无响应",
        "Тест неполный" to "测试未完成",
        "Android не выдал разрешение на VPN" to "Android 未授予 VPN 权限",
        "Android не открыл запрос разрешения VPN" to "Android 未能打开 VPN 权限请求",
        "Android требует разрешение на VPN" to "Android 需要 VPN 权限",
        "Конфиг пустой." to "配置为空。",
        "VPN не запустился" to "VPN 未能启动",
        "VPN не запустился: внутренний сервис не ответил" to "VPN 未能启动：内部服务无响应",
        "VPN не запустился: локальный порт проверки занят" to "VPN 未能启动：本地检测端口已被占用",
        "QR найден, но это не профиль VLESS/Hysteria2" to "已识别二维码，但其中不是 VLESS/Hysteria2 配置",
    )

    fun text(
        source: String,
        selected: AppLanguage,
        systemLanguage: String = Locale.getDefault().language,
    ): String {
        val language = resolveAppLanguage(selected, systemLanguage)
        if (language == AppLanguage.Russian) return source
        val translations = english
        translations[source]?.let { return it }

        return when {
            source.startsWith("Профиль «") && source.endsWith("» будет удалён.") ->
                "Profile “${source.removePrefix("Профиль «").removeSuffix("» будет удалён.")}” will be deleted."
            source.startsWith("Импортировано профилей: ") ->
                "Profiles imported: ${source.substringAfter(": ")}"
            source.startsWith("Ошибка загрузки подписки: ") ->
                "Subscription loading failed: ${text(source.substringAfter(": "), selected, systemLanguage)}"
            source.startsWith("Профиль содержит пока неподдерживаемый транспорт: ") ->
                "The profile uses an unsupported transport: ${source.substringAfterLast(": ")}"
            source.startsWith("Профиль содержит неподдерживаемый режим XHTTP: ") ->
                "The profile uses an unsupported XHTTP mode: ${source.substringAfterLast(": ")}"
            source.startsWith("Профиль не подключился: ") ->
                "The profile failed: ${text(source.substringAfter(": "), selected, systemLanguage)}"
            source.startsWith("Не удалось измерить: ") ->
                "Could not measure: ${translateMeasurements(source.substringAfter(": "))}"
            source.startsWith("Конфиг не собирается: ") ->
                "Could not build the configuration: ${source.substringAfter(": ")}"
            source.startsWith("DNS не вернул адреса для ") ->
                "DNS returned no addresses for ${source.substringAfter("для ")}"
            source.startsWith("DNS не нашел сервер ") ->
                "DNS could not resolve ${source.substringAfter("сервер ")}"
            source.startsWith("Базовая проверка пройдена: конфиг собран, DNS нашел ") ->
                "Basic check passed: the configuration is valid and DNS resolved " +
                    source.substringAfter("DNS нашел ").substringBefore('.') +
                    ". Hysteria2 uses UDP, so final verification runs when the VPN starts."
            source.startsWith("Базовая проверка пройдена: конфиг собран, DNS работает, TCP ") ->
                "Basic check passed: the configuration and DNS are valid; TCP " +
                    source.substringAfter("TCP ")
                        .replace(" отвечает за ", " responded in ")
                        .replace(" мс", " ms")
            source.startsWith("Сервер ") && source.contains(" не отвечает по TCP: ") ->
                "Server ${source.substringAfter("Сервер ").substringBefore(" не отвечает")} is not responding over TCP: " +
                    source.substringAfter("не отвечает по TCP: ")
            source.startsWith("Исключить выбранные: ") ->
                "Exclude selected: ${source.substringAfterLast(": ")}"
            source.startsWith("Только выбранные: ") ->
                "Only selected: ${source.substringAfterLast(": ")}"
            source.endsWith(" мс") -> source.removeSuffix(" мс") + " ms"
            source.endsWith(" КБ/с") -> source.removeSuffix(" КБ/с") + " KB/s"
            source.endsWith(" МБ/с") -> source.removeSuffix(" МБ/с") + " MB/s"
            source.endsWith(" Мбит/с") -> source.removeSuffix(" Мбит/с") + " Mbps"
            else -> source
        }
    }

    private fun translateMeasurements(value: String): String = value
        .replace("пинг", "latency", ignoreCase = true)
        .replace("загрузка", "download", ignoreCase = true)
        .replace("отдача", "upload", ignoreCase = true)
}
